# **<font color="red">Email Spam Detection</font>**

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("../data/spam.csv")

print("-"*80)
print(df.columns)
print("-"*80)
print(df.isna().sum())
print("-"*80)
df.head()

--------------------------------------------------------------------------------
Index(['Category', 'Message'], dtype='object')
--------------------------------------------------------------------------------
Category    0
Message     0
dtype: int64
--------------------------------------------------------------------------------

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [3]:
df['Spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)
df.head()

  Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

## **<font color="blue">Naive Bayes</font>**

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

X_train,X_test,y_train,y_test=train_test_split(df.Message, df.Spam, test_size=0.25)

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

clf.fit(X_train,y_train)

emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

clf.predict(emails)
clf.score(X_test,y_test)

0.9899497487437185