# **<font color="red">Accuracy and Confusion Matrix</font>**

## **<font color="blue">Data Visualization</font>**

In [1]:
import pandas as pd

df = pd.read_csv("../data/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
df.shape

(150, 6)

In [3]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [6]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [7]:
y = df['Species']
X = df.drop(columns=['Species'])

# # if target column is always last column then use this technique
# X = df.iloc[:, :-1]
# y = df.iloc[:, -1]

X.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [8]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

## **<font color="blue">Model Predictions and Score</font>**

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv("../data/Iris.csv")

y = df['Species']
X = df.drop(columns=['Species'])

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# model
lrc = LogisticRegression()
dtc = DecisionTreeClassifier()

# train
lrc.fit(X_train, y_train)
dtc.fit(X_train, y_train)

# test
y_pred_lrc = lrc.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

print("="*80)
print("Accuracy Score: ")
print("Logistic_Regression_Accuracy: ", accuracy_score(y_test, y_pred_lrc))
print("Decision_Tree_Accuracy: ", accuracy_score(y_test, y_pred_dtc))
print("="*80)
print("="*80)
print("Confusion Matrix: ")
print("Logistic_Regression_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_lrc))
print("Decision_Tree_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_dtc))
print("="*80)

================================================================================
Accuracy Score:
Logistic_Regression_Accuracy:  1.0
Decision_Tree_Accuracy:  1.0
================================================================================
================================================================================
Confusion Matrix:
Logistic_Regression_Confusion_Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Decision_Tree_Confusion_Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
================================================================================

D:\Study\machineLearning\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(