# **<font color="red">Accuracy and Confusion Matrix</font>**

## **<font color="blue">Data Visualization</font>**

In [1]:
import pandas as pd

df = pd.read_csv("../data/mnist/mnist_train.csv")
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
df.shape

(60000, 785)

In [3]:
df.isnull().sum()

label    0
1x1      0
1x2      0
1x3      0
1x4      0
        ..
28x24    0
28x25    0
28x26    0
28x27    0
28x28    0
Length: 785, dtype: int64

In [4]:
df.describe()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
count,60000.000000,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,60000.0,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.0000,60000.0,60000.0,60000.0,60000.0
mean,4.453933,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.200433,0.088867,0.045633,0.019283,0.015117,0.0020,0.0,0.0,0.0,0.0
std,2.889270,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.042472,3.956189,2.839845,1.686770,1.678283,0.3466,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.000000,254.000000,62.0000,0.0,0.0,0.0,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB

In [6]:
df['label'].unique()

array([5, 0, 4, 1, 9, 2, 3, 6, 7, 8], dtype=int64)

In [7]:
train = pd.read_csv("../data/mnist/mnist_train.csv")
test = pd.read_csv("../data/mnist/mnist_test.csv")

print(train.shape, test.shape)

(60000, 785) (10000, 785)

In [12]:
X_test = train['label']
X_train = train.drop(columns=['label'])

y_test = test['label']
y_train = test.drop(columns=['label'])

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(60000, 784) (60000,) (10000, 784) (10000,)

## **<font color="blue">Model Predictions and Score</font>**

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# data loading
train = pd.read_csv("../data/mnist/mnist_train.csv")
test = pd.read_csv("../data/mnist/mnist_test.csv")

# split X and y correctly
X_train = train.drop(columns=['label'])
y_train = train['label']

X_test = test.drop(columns=['label'])
y_test = test['label']

# model
lrc = LogisticRegression()
dtc = DecisionTreeClassifier()

# train
lrc.fit(X_train, y_train)
dtc.fit(X_train, y_train)

# test
y_pred_lrc = lrc.predict(X_test)
y_pred_dtc = dtc.predict(X_test)

print("="*80)
print("Accuracy Score: ")
print("Logistic_Regression_Accuracy: ", accuracy_score(y_test, y_pred_lrc))
print("Decision_Tree_Accuracy: ", accuracy_score(y_test, y_pred_dtc))
print("="*80)
print("="*80)
print("Confusion Matrix: ")
print("Logistic_Regression_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_lrc))
print("Decision_Tree_Confusion_Matrix: \n", confusion_matrix(y_test, y_pred_dtc))
print("="*80)

D:\Study\machineLearning\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

================================================================================
Accuracy Score:
Logistic_Regression_Accuracy:  0.9255
Decision_Tree_Accuracy:  0.8749
================================================================================
================================================================================
Confusion Matrix:
Logistic_Regression_Confusion_Matrix:
 [[ 963    0    0    3    1    3    4    4    2    0]
 [   0 1112    4    2    0    1    3    2   11    0]
 [   3   10  926   15    6    4   15    8   42    3]
 [   4    1   21  916    1   26    3    9   22    7]
 [   1    1    7    3  910    0    9    7   10   34]
 [  11    2    1   33   11  776   11    6   35    6]
 [   9    3    7    3    7   16  910    2    1    0]
 [   1    6   24    5    7    1    0  951    3   30]
 [   8    7    6   23    6   26   10   10  869    9]
 [   9    7    0   11   25    6    0   22    7  922]]
Decision_Tree_Confusion_Matrix:
 [[ 915    0    6    6    7   14   16    3    8    5]
 [   2 1089   12    5    1    4    7    2   11    2]
 [  14    8  881   31   18    7   11   24   28   10]
 [   8    7   33  856    8   44    5    8   22   19]
 [   8    5   10    7  854    6   15   12   19   46]
 [  15    7    4   48    6  736   19    6   34   17]
 [  14    6   11    9   19   19  850    2   23    5]
 [   4   11   23   16    7    9    3  926    7   22]
 [  12    6   30   38   19   23   20   10  791   25]
 [  13    2    5   22   47    9    8   24   28  851]]
================================================================================